remote_theme: mmistakes/minimal-mistakes

minimal_mistakes_skin: "dark"

title: "profile"
name: "saad"
description: "Cybersecurity Student | Aspiring Security Professional"
url: "https://saad.github.io"

plugins:
  - jekyll-include-cache
